/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.*;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import pharmacy.Tools;

/**
 *
 * @author Mohamed
 */
public class Company extends javax.swing.JFrame {

    /**
     * Creates new form Company
     */
    public Company() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    String username;

    public Company(String name) {
        initComponents();
        this.username = name;
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ID = new control.JTextBox(20);
        txt_name = new control.JTextBox(20);
        txt_address = new control.JTextBox(20);
        txt_phone = new control.JTextBox(20);
        jScrollPane1 = new javax.swing.JScrollPane();
        tblphones = new javax.swing.JTable();
        btn_addPhone = new control.JMyButton();
        btn_removePhone = new control.JMyButton();
        btn_removePhone1 = new control.JMyButton();
        btn_add = new control.JMyButton();
        btn_up = new control.JMyButton();
        btn_del = new control.JMyButton();
        btn_clear = new control.JMyButton();
        btn_sel = new control.JMyButton();
        btn_find = new control.JMyButton();
        btn_back = new control.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        rad_ID = new javax.swing.JRadioButton();
        rad_name = new javax.swing.JRadioButton();
        rad_address = new javax.swing.JRadioButton();
        rad_phone = new javax.swing.JRadioButton();
        txt_search = new control.JTextBox(20);
        btn_addPhone1 = new control.JMyButton();
        jMyButton8 = new control.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("Company");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Logged as :");

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("jLabel3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Company ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Company Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Company Address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Company Phones :");

        txt_ID.setEditable(false);
        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phoneKeyPressed(evt);
            }
        });

        tblphones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "phones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblphones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphonesMouseClicked(evt);
            }
        });
        tblphones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblphonesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblphones);

        btn_addPhone.setText("Add Phone");
        btn_addPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPhoneActionPerformed(evt);
            }
        });

        btn_removePhone.setText("Remove All");
        btn_removePhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_removePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePhoneActionPerformed(evt);
            }
        });

        btn_removePhone1.setText("Remove this");
        btn_removePhone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_removePhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePhone1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_removePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_removePhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removePhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_add.setText("ADD");
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_add.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_up.setText("Update");
        btn_up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_up.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_up.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upActionPerformed(evt);
            }
        });

        btn_del.setText("Delete");
        btn_del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_del.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_del.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_clear.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_sel.setText("Display");
        btn_sel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sel.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_sel.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selActionPerformed(evt);
            }
        });

        btn_find.setText("Find");
        btn_find.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_find.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_find.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_back.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_back.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company ID", "Company Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Search by");

        rad_ID.setBackground(new java.awt.Color(255, 255, 255));
        rad_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_ID.setText("ID");

        rad_name.setBackground(new java.awt.Color(255, 255, 255));
        rad_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_name.setText("Name");

        rad_address.setBackground(new java.awt.Color(255, 255, 255));
        rad_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_address.setText("Address");

        rad_phone.setBackground(new java.awt.Color(255, 255, 255));
        rad_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_phone.setText("Phones");

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        btn_addPhone1.setText("Search");
        btn_addPhone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPhone1ActionPerformed(evt);
            }
        });

        jMyButton8.setText("Log out");
        jMyButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMyButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_user)
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rad_ID)
                                        .addGap(10, 10, 10)
                                        .addComponent(rad_name)
                                        .addGap(10, 10, 10)
                                        .addComponent(rad_address)
                                        .addGap(10, 10, 10)
                                        .addComponent(rad_phone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_addPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbl_user))
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rad_ID)
                            .addComponent(rad_name)
                            .addComponent(rad_address)
                            .addComponent(rad_phone))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    company c = new company();

    private void clear() {
        Tools.clear(this);
        txt_ID.setText(c.getAutoNumber());
        removePhones();
        btn_add.setEnabled(true);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);
        txt_name.requestFocus();
    }

    private void set() {
        c.setID(Integer.parseInt(txt_ID.getText()));
        c.setName(txt_name.getText());
        c.setAddress(txt_address.getText());
    }

    private void add() {
        set();
        c.add();

        cp.setID(Integer.parseInt(txt_ID.getText()));
        for (int i = 0; i < tblphones.getRowCount(); i++) {
            cp.setPhone(tblphones.getValueAt(i, 0).toString());
            cp.add();
        }

        clear();
        c.selectAll(tbl);
        removePhones();
    }

    private void update() {
        set();
        c.update();

        cp.setID(Integer.parseInt(txt_ID.getText()));
        //delete all phones for this employee
        cp.deleteAllPhones();
        //add phones again for this employee
        for (int i = 0; i < tblphones.getRowCount(); i++) {
            cp.setPhone(tblphones.getValueAt(i, 0).toString());
            cp.add();
        }

        clear();
        c.selectAll(tbl);
        removePhones();
    }

    private void delete() {
        if (Tools.ConfirmMsg("Are You Sure You Want to Delete this Company ?")) {
            cp.setID(Integer.parseInt(txt_ID.getText()));
            cp.deleteAllPhones();

            set();
            c.delete();
            clear();
            c.selectAll(tbl);
            removePhones();
        }
    }

    private String mylike() {
        return " like '%" + txt_search.getText() + "%'";
    }

    private void search() {
        String txtSer;
        String query = "SELECT * FROM `company` WHERE ";
        if (rad_ID.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "ID" + mylike();

        } else if (rad_name.isSelected()) {
            txtSer = Tools.removenum(txt_search.getText());
            query += "Name" + mylike();
        } else if (rad_address.isSelected()) {
            txtSer = txt_search.getText();
            query += "Address" + mylike();
        } else {
            String str = cp.getCompByPhone(txt_search.getText());
            //txtSer = Tools.getnum(str);
            query += "ID like '%" + str + "%'";
        }

        c.getCustom(query, tbl);

        if (tbl.getRowCount() <= 0) {
            Tools.msg("Can't Find any information");
            c.selectAll(tbl);
            txt_search.setText("");
        }
    }

    company_phones cp = new company_phones();

    private void addPhones() {
        DefaultTableModel model = (DefaultTableModel) tblphones.getModel();
        model.addRow(new Object[]{txt_phone.getText()});
        txt_phone.setText(null);
        txt_phone.requestFocus();
    }

    private void removePhones() {
        DefaultTableModel model = (DefaultTableModel) tblphones.getModel();
        model.setNumRows((0));
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_user.setText(username);
        btn_group.add(rad_ID);
        btn_group.add(rad_name);
        btn_group.add(rad_address);
        btn_group.add(rad_phone);
        clear();
        c.selectAll(tbl);
        tbl.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        main m = new main(username);
        m.setTitle("Main Menu");
        this.dispose();
        Tools.open(m);
    }//GEN-LAST:event_btn_backActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        try {
            int row = tbl.getSelectedRow();
            String ID = tbl.getValueAt(row, 0).toString();
            String name = tbl.getValueAt(row, 1).toString();
            String add = tbl.getValueAt(row, 2).toString();

            txt_ID.setText(ID);
            txt_name.setText(name);
            txt_address.setText(add);

            txt_phone.setText("");
            cp.setID(Integer.parseInt(txt_ID.getText()));
            cp.selectAll(tblphones);

            btn_add.setEnabled(false);
            btn_up.setEnabled(true);
            btn_del.setEnabled(true);
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_tblMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        /*btn_add.setEnabled(true);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);*/
        clear();
        //txt_ID.setText(c.getAutoNumber());

    }//GEN-LAST:event_jPanel1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_formMouseClicked

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        String strname = (String) Tools.InputBox("Enter The Comapany Name:");
        //c.setName(strname);
        String ID = c.getValueByName(strname);
        c.setID(Integer.parseInt(ID));
        c.selectOneRow(tbl);
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selActionPerformed
        // TODO add your handling code here:
        c.selectAll(tbl);
    }//GEN-LAST:event_btn_selActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btn_upActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_addPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPhone1ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btn_addPhone1ActionPerformed

    private void btn_addPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPhoneActionPerformed
        // TODO add your handling code here:
        addPhones();
    }//GEN-LAST:event_btn_addPhoneActionPerformed

    private void btn_removePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePhoneActionPerformed
        // TODO add your handling code here:
        removePhones();
    }//GEN-LAST:event_btn_removePhoneActionPerformed

    private void tblphonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphonesMouseClicked
        // TODO add your handling code here:
        int row = tblphones.getSelectedRow();
        txt_phone.setText(tblphones.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblphonesMouseClicked

    private void btn_removePhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePhone1ActionPerformed
        // TODO add your handling code here:
        String query = "delete from company_phones where Phone = '" + txt_phone.getText() + "'";
        db.database.RunNonQuery(query);
        txt_phone.setText("");
        int row = tblphones.getSelectedRow();
        String deleted = tblphones.getValueAt(row, 0).toString();
        ((DefaultTableModel) tblphones.getModel()).removeRow(row);
    }//GEN-LAST:event_btn_removePhone1ActionPerformed

    private void txt_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_CONTROL:
                addPhones();
                break;
            case KeyEvent.VK_ENTER:
                add();
                break;
            case KeyEvent.VK_ESCAPE:
                main m = new main(username);
                m.setTitle("Main Menu");
                this.dispose();
                Tools.open(m);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_phoneKeyPressed

    private void jMyButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton8ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setTitle("Login");
        this.dispose();
        Tools.open(log);
    }//GEN-LAST:event_jMyButton8ActionPerformed

    private void tblphonesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblphonesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            String query = "delete from company_phones where Phone = '" + txt_phone.getText() + "'";
            db.database.RunNonQuery(query);
            txt_phone.setText("");
            int row = tblphones.getSelectedRow();
            String deleted = tblphones.getValueAt(row, 0).toString();
            ((DefaultTableModel) tblphones.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_tblphonesKeyPressed

    private void tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_DELETE) {
            delete();
        }
    }//GEN-LAST:event_tblKeyPressed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            search();
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private control.JMyButton btn_add;
    private control.JMyButton btn_addPhone;
    private control.JMyButton btn_addPhone1;
    private control.JMyButton btn_back;
    private control.JMyButton btn_clear;
    private control.JMyButton btn_del;
    private control.JMyButton btn_find;
    private javax.swing.ButtonGroup btn_group;
    private control.JMyButton btn_removePhone;
    private control.JMyButton btn_removePhone1;
    private control.JMyButton btn_sel;
    private control.JMyButton btn_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private control.JMyButton jMyButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JRadioButton rad_ID;
    private javax.swing.JRadioButton rad_address;
    private javax.swing.JRadioButton rad_name;
    private javax.swing.JRadioButton rad_phone;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tblphones;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
