/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import pharmacy.Tools;


/**
 *
 * @author Mohamed
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(new GridBagLayout());
        add(pnl, new GridBagConstraints());
    }
    String username;
    public main(String name) {
        initComponents();
        this.username = name;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(new GridBagLayout());
        add(pnl, new GridBagConstraints());
    }
    
    private void importdata() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        jMyButton7 = new control.JMyButton();
        lbl_user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout1 = new log.logout();
        pOS1 = new sales.POS();
        barCode1 = new BarCode.BarCode();
        stock2 = new stock2.stock();
        comp1 = new comp.comp();
        emp1 = new emp.emp();
        repo1 = new Rep.repo();
        im = new log.logout();
        ex = new control.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl.setBackground(new java.awt.Color(255, 255, 255));

        jMyButton7.setText("Exit");
        jMyButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMyButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton7ActionPerformed(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Logged as :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Main Menu");

        logout1.setText("logout");
        logout1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        pOS1.setText("Point Of Sales");
        pOS1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pOS1ActionPerformed(evt);
            }
        });

        barCode1.setText("Print BarCode");
        barCode1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        barCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCode1ActionPerformed(evt);
            }
        });

        stock2.setText("Stock");
        stock2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock2ActionPerformed(evt);
            }
        });

        comp1.setText("Company");
        comp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp1ActionPerformed(evt);
            }
        });

        emp1.setText("Employee");
        emp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp1ActionPerformed(evt);
            }
        });

        repo1.setText("Report");
        repo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        repo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repo1ActionPerformed(evt);
            }
        });

        im.setText("import Data");
        im.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        im.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imActionPerformed(evt);
            }
        });

        ex.setText("Export Data");
        ex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_user))
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emp1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(im, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(repo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMyButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repo1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(im, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_user))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_user.setText(username);
    }//GEN-LAST:event_formWindowOpened

    private void jMyButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMyButton7ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setTitle("Login");
        this.dispose();
        Tools.open(log);
    }//GEN-LAST:event_logout1ActionPerformed

    private void pOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pOS1ActionPerformed
        // TODO add your handling code here:
        POS p = new POS(username);
        p.setTitle("Point Of Sales (POS)");
        this.dispose();
        Tools.open(p);
    }//GEN-LAST:event_pOS1ActionPerformed

    private void barCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCode1ActionPerformed
        // TODO add your handling code here:
        barcode bar = new barcode(username);
        bar.setTitle("BarCode Printing");
        this.dispose();
        Tools.open(bar);
    }//GEN-LAST:event_barCode1ActionPerformed

    private void stock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock2ActionPerformed
        // TODO add your handling code here:
        Stock s = new Stock(username);
        s.setTitle("Stock of Drugs");
        this.dispose();
        Tools.open(s);
    }//GEN-LAST:event_stock2ActionPerformed

    private void comp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1ActionPerformed
        // TODO add your handling code here:
        Company comp = new Company(username);
        comp.setTitle("Company");
        this.dispose();
        Tools.open(comp);
    }//GEN-LAST:event_comp1ActionPerformed

    private void emp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp1ActionPerformed
        // TODO add your handling code here:
        confirm2 emp = new confirm2(username);
        emp.setTitle("Password Confirmation");
        this.dispose();
        Tools.open(emp);
    }//GEN-LAST:event_emp1ActionPerformed

    private void repo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repo1ActionPerformed
        // TODO add your handling code here:
        submain rep = new submain(username);
        rep.setTitle("Main Report");
        this.dispose();
        Tools.open(rep);
    }//GEN-LAST:event_repo1ActionPerformed

    
    
    private void imActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imActionPerformed
        // TODO add your handling code here:
        importdata im = new importdata(username);
        im.setTitle("Importing data");
        this.dispose();
        Tools.open(im);
    }//GEN-LAST:event_imActionPerformed

    java.sql.ResultSet rs;
    PreparedStatement insert;
    java.sql.Connection con;
    java.sql.Statement stmt;
    
    //===============================================================================
    private void export_sales_prod() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
        } catch (ClassNotFoundException | SQLException e) {
            Tools.msg(e.getMessage());
        }
        //export sales_product table
        String csvFilePath = "D://sales_product.csv";
        
        try {
            //String sql = "select ID,Name,Address from company";
            String sql = "select ID,Sales_ID,Barcode,Total,Price,QTY,Typee,User,isRet from sales_product";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            FileOutputStream file = new FileOutputStream(csvFilePath);
            OutputStreamWriter fileWriter = new OutputStreamWriter(file, StandardCharsets.UTF_8);
            fileWriter.write("ID,Bill_NO,Barcode,Total,Price,QTY,Type,User_ID,is_retrieved");
            while (rs.next()) {
                int ID = rs.getInt("ID");
                int sales_ID = rs.getInt("Sales_ID");
                String bar = rs.getString("Barcode");
                double total = rs.getDouble("Total");
                double price = rs.getDouble("Price");
                int qty = rs.getInt("QTY");
                String type = rs.getString("Typee");
                int user = rs.getInt("User");
                boolean ret = rs.getBoolean("isRet");
                String line;
                line = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s",
                        ID,sales_ID,bar,total,price,qty,type,user,ret);
                //fileWriter.newLine();
                fileWriter.write("\n");
                fileWriter.write(line);
            }
            stmt.close();
            fileWriter.close();
            Tools.msg("Data exported successfully from sales_product");
            
        } catch (SQLException | IOException e) {
            Tools.msg(e.getMessage());
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
            String sql = "delete from sales_product";
            stmt = con.createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }
    
    //===============================================================================
    private void export_ret() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
        } catch (ClassNotFoundException | SQLException e) {
            Tools.msg(e.getMessage());
        }
        //export sales_product table
        String csvFilePath = "D://retrieve.csv";
        
        try {
            //String sql = "select ID,Name,Address from company";
            String sql = "select ID,Sales_ID,Drug_Name,Typee,QTY,price,Total,Barcode,Username,Datee from retrieve";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            FileOutputStream file = new FileOutputStream(csvFilePath);
            OutputStreamWriter fileWriter = new OutputStreamWriter(file, StandardCharsets.UTF_8);
            fileWriter.write("Retrieved_NO,Bill_NO,Drug_Name,Type,QTY,price,Total,Barcode,Username,Date");
            while (rs.next()) {
                int ID = rs.getInt("ID");
                int sales_ID = rs.getInt("Sales_ID");
                String name = rs.getString("Drug_Name");
                String type = rs.getString("Typee");
                double qty = rs.getDouble("QTY");
                double price = rs.getDouble("price");               
                double total = rs.getDouble("Total");
                String bar = rs.getString("Barcode");             
                String user = rs.getString("Username");
                String date = rs.getString("Datee");
                String line;
                line = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s",
                        ID,sales_ID,name,type,qty,price,total,bar,user,date);

                //fileWriter.newLine();
                fileWriter.write("\n");
                fileWriter.write(line);
            }
            stmt.close();
            fileWriter.close();
            Tools.msg("Data exported successfully from retrieve");
            
        } catch (SQLException | IOException e) {
            Tools.msg(e.getMessage());
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
            String sql = "delete from retrieve";
            stmt = con.createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }
    
    //===============================================================================
    private void export_sales() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
        } catch (ClassNotFoundException | SQLException e) {
            Tools.msg(e.getMessage());
        }
        //export sales_product table
        String csvFilePath = "D://sales.csv";
        
        try {
            //String sql = "select ID,Name,Address from company";
            String sql = "select ID,Datee,Subtotal,Pay,Balance from sales";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            FileOutputStream file = new FileOutputStream(csvFilePath);
            OutputStreamWriter fileWriter = new OutputStreamWriter(file, StandardCharsets.UTF_8);
            fileWriter.write("Bill_NO,Date,Total,Paid,Balance");
            while (rs.next()) {
                int ID = rs.getInt("ID");
                String date = rs.getString("Datee");               
                double total = rs.getDouble("Subtotal");
                double pay = rs.getDouble("Pay");
                double balance = rs.getDouble("Balance");             
                String line;
                line = String.format("%s,%s,%s,%s,%s",
                        ID,date,total,pay,balance);

                //fileWriter.newLine();
                fileWriter.write("\n");
                fileWriter.write(line);
            }
            stmt.close();
            fileWriter.close();
            Tools.msg("Data exported successfully from sales");
            
        } catch (SQLException | IOException e) {
            //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, e);
            Tools.msg(e.getMessage());
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
            String sql = "delete from sales";
            stmt = con.createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }
    
    //===============================================================================
    
    
    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
        // TODO add your handling code here:
        export_sales_prod();
        export_ret();
        export_sales();
    }//GEN-LAST:event_exActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BarCode.BarCode barCode1;
    private comp.comp comp1;
    private emp.emp emp1;
    private control.JMyButton ex;
    private log.logout im;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private control.JMyButton jMyButton7;
    private javax.swing.JLabel lbl_user;
    private log.logout logout1;
    private sales.POS pOS1;
    private javax.swing.JPanel pnl;
    private Rep.repo repo1;
    private stock2.stock stock2;
    // End of variables declaration//GEN-END:variables
}
