/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.*;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import pharmacy.Tools;

/**
 *
 * @author Mohamed
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        /*cmx_type.addItem("Bills");
        cmx_type.addItem("Injection");
        cmx_type.addItem("Drink");
         */
        cmx_type.addItem("علبة");
        //cmx_type.addItem("شريط");
        /*cmx_type.addItem("زجاجة");
        cmx_type.addItem("امبول");
        cmx_type.addItem("كيس");
        cmx_type.addItem("انبوبة");*/
    }

    String username;

    public Stock(String name) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.username = name;

        cmx_type.addItem("علبة");
        //cmx_type.addItem("شريط");
        /*cmx_type.addItem("زجاجة");
        cmx_type.addItem("امبول");
        cmx_type.addItem("كيس");
        cmx_type.addItem("انبوبة");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ID = new control.JTextBox(20);
        jLabel4 = new javax.swing.JLabel();
        txt_name = new control.JTextBox(20);
        jLabel5 = new javax.swing.JLabel();
        txt_bar = new control.JTextBox(20);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_price = new control.JTextBox(20);
        jLabel8 = new javax.swing.JLabel();
        txt_qty = new control.JTextBox(20);
        jLabel9 = new javax.swing.JLabel();
        cmx_comp = new control.JMyCompo();
        cmx_type = new control.JMyCompo();
        add_comp = new control.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        rad_ID = new javax.swing.JRadioButton();
        rad_bar = new javax.swing.JRadioButton();
        rad_name = new javax.swing.JRadioButton();
        rad_comp = new javax.swing.JRadioButton();
        rad_type = new javax.swing.JRadioButton();
        rad_price = new javax.swing.JRadioButton();
        rad_qty = new javax.swing.JRadioButton();
        txt_search = new control.JTextBox(20);
        btn_addPhone1 = new control.JMyButton();
        btn_add = new control.JMyButton();
        btn_up = new control.JMyButton();
        btn_del = new control.JMyButton();
        btn_back = new control.JMyButton();
        jMyButton8 = new control.JMyButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_tab = new control.JTextBox(10);
        rad_tab = new javax.swing.JRadioButton();
        btn_del1 = new control.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Logged as :");

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Drug ID :");

        txt_ID.setEditable(false);
        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Drug Name :");

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("BarCode :");

        txt_bar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_barKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Type :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Price per box:");

        txt_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_priceKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("QTY :");

        txt_qty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Company :");

        cmx_comp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmx_compKeyPressed(evt);
            }
        });

        cmx_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmx_typeKeyPressed(evt);
            }
        });

        add_comp.setText("Add new");
        add_comp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_compActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BarCode", "Name", "Company ID", "Company Name", "Type", "Price", "Qty", "Strip"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Search By :");

        rad_ID.setBackground(new java.awt.Color(255, 255, 255));
        rad_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_ID.setText("ID");

        rad_bar.setBackground(new java.awt.Color(255, 255, 255));
        rad_bar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_bar.setText("BarCode");

        rad_name.setBackground(new java.awt.Color(255, 255, 255));
        rad_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_name.setText("Name");

        rad_comp.setBackground(new java.awt.Color(255, 255, 255));
        rad_comp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_comp.setText("Company");

        rad_type.setBackground(new java.awt.Color(255, 255, 255));
        rad_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_type.setText("Type");

        rad_price.setBackground(new java.awt.Color(255, 255, 255));
        rad_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_price.setText("Price");

        rad_qty.setBackground(new java.awt.Color(255, 255, 255));
        rad_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_qty.setText("QTY");

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        btn_addPhone1.setText("Search");
        btn_addPhone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPhone1ActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_up.setText("Update");
        btn_up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upActionPerformed(evt);
            }
        });

        btn_del.setText("Delete");
        btn_del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_back.setMaximumSize(new java.awt.Dimension(59, 25));
        btn_back.setMinimumSize(new java.awt.Dimension(59, 25));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jMyButton8.setText("Log out");
        jMyButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMyButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton8ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("Stock of Drugs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Units ber box :");

        txt_tab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tabKeyPressed(evt);
            }
        });

        rad_tab.setBackground(new java.awt.Color(255, 255, 255));
        rad_tab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_tab.setText("Strip");

        btn_del1.setText("Display All");
        btn_del1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cmx_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_user)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 215, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(230, 230, 230)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmx_type, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_ID)
                                .addGap(10, 10, 10)
                                .addComponent(rad_bar)
                                .addGap(10, 10, 10)
                                .addComponent(rad_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_comp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_type)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad_qty))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_del1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rad_tab, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_addPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_user))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmx_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmx_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rad_ID)
                    .addComponent(rad_bar)
                    .addComponent(rad_name)
                    .addComponent(rad_comp)
                    .addComponent(rad_type)
                    .addComponent(rad_price)
                    .addComponent(rad_qty))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rad_tab)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_addPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_up, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_del1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    stock s = new stock();

    private void clear() {
        Tools.clear(this);
        txt_bar.requestFocus();
        btn_add.setEnabled(true);
        btn_up.setEnabled(false);
        btn_del.setEnabled(false);

        txt_ID.setText(s.getAutoNumber());
    }

    private void set() {
        String comp = cmx_comp.getSelectedItem().toString();
        String type = cmx_type.getSelectedItem().toString();

        int Comp_ID = Integer.parseInt(s.getValueByName(comp));

        s.setID(Integer.parseInt(txt_ID.getText()));
        s.setComp_ID(Comp_ID);
        s.setBarcode(txt_bar.getText());
        s.setName(txt_name.getText());
        s.setPrice(Double.parseDouble(txt_price.getText()));
        s.setQty(Double.parseDouble(txt_qty.getText()));
        s.setTypee(type);
        //s.setTab(Integer.parseInt(txt_tab.getText()));
    }

    private boolean checkfoundation() {
        boolean check = db.database.checkinsertion(txt_bar.getText());
        return check;
    }

    private void add() {
        checkfoundation();
        char str[] = txt_price.getText().toCharArray();
        for (int i = 0; i < str.length; i++) {
            if (!(str[i] == '.' || str[i] == '1' || str[i] == '2' || str[i] == '3' || str[i] == '4' || str[i] == '5' || str[i] == '6' || str[i] == '7' || str[i] == '8' || str[i] == '9' || str[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_price.setText("");
                txt_price.requestFocus();
                break;
            }
        }
        char strqty[] = txt_qty.getText().toCharArray();
        for (int i = 0; i < strqty.length; i++) {
            if (!(strqty[i] == '.' || strqty[i] == '1' || strqty[i] == '2' || strqty[i] == '3' || strqty[i] == '4' || strqty[i] == '5' || strqty[i] == '6' || strqty[i] == '7' || strqty[i] == '8' || strqty[i] == '9' || strqty[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_qty.setText("");
                txt_qty.requestFocus();
                break;
            }
        }
        char strtab[] = txt_tab.getText().toCharArray();
        for (int i = 0; i < strtab.length; i++) {
            if (!(strtab[i] == '1' || strtab[i] == '2' || strtab[i] == '3' || strtab[i] == '4' || strtab[i] == '5' || strtab[i] == '6' || strtab[i] == '7' || strtab[i] == '8' || strtab[i] == '9' || strtab[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_tab.setText("");
                txt_tab.requestFocus();
                break;
            }
        }

        if ("".equals(txt_bar.getText())) {
        } else {
            set();
            //=======================================================================
            boolean check;

            /*try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?useUnicode=true&characterEncoding=UTF-8&serverTimezone = UTC", "root", "");
            } catch (Exception ex) {
                Tools.msg(ex.getMessage());
            }*/
            check = db.database.checkinsertion(txt_bar.getText());
            if (check) {
                String update_qty = "Update drug set Qty = Qty + " + Double.parseDouble(txt_qty.getText()) + " where Barcode = '" + txt_bar.getText() + "'";
                db.database.RunNonQuery(update_qty);
            } else if (check == false) {
                if (!"علبة".equals(cmx_type.getSelectedItem())) {
                    String Comp_ID = s.getValueByName(cmx_comp.getSelectedItem().toString());
                    String sql = "insert into drug (ID,Name,Barcode,Price,Comp_ID,Typee,Qty) values ("
                            + Integer.parseInt(txt_ID.getText()) + " , "
                            + " '" + txt_name.getText() + "' , "
                            + " '" + txt_bar.getText() + "' , "
                            + Double.parseDouble(txt_price.getText()) + " , "
                            + Integer.parseInt(Comp_ID) + " , "
                            + " '" + cmx_type.getSelectedItem().toString() + "' , "
                            + Double.parseDouble(txt_qty.getText()) + ")";
                    check = db.database.RunNonQuery(sql);
                } else if ("علبة".equals(cmx_type.getSelectedItem())) {
                    String Comp_ID = s.getValueByName(cmx_comp.getSelectedItem().toString());
                    String sql = "insert into drug (ID,Name,Barcode,Price,Comp_ID,Typee,Qty,Tab) values ("
                            + Integer.parseInt(txt_ID.getText()) + " , "
                            + " '" + txt_name.getText() + "' , "
                            + " '" + txt_bar.getText() + "' , "
                            + Double.parseDouble(txt_price.getText()) + " , "
                            + Integer.parseInt(Comp_ID) + " , "
                            + " '" + cmx_type.getSelectedItem().toString() + "' , "
                            + Double.parseDouble(txt_qty.getText()) + " , "
                            + Integer.parseInt(txt_tab.getText()) + ")";
                    check = db.database.RunNonQuery(sql);
                }
            }
            //=======================================================================
            //s.add();
            clear();
            s.selectAll(tbl);

            /*txt_name.setEditable(true);
            txt_price.setEditable(true);
            txt_tab.setEditable(true);
            cmx_type.setEnabled(true);
            cmx_comp.setEnabled(true);
            btn_addPhone1.setEnabled(true);
            add_comp.setEnabled(true);*/
        }
    }

    private void update() {
        char str[] = txt_price.getText().toCharArray();
        for (int i = 0; i < str.length; i++) {
            if (!(str[i] == '.' || str[i] == '1' || str[i] == '2' || str[i] == '3' || str[i] == '4' || str[i] == '5' || str[i] == '6' || str[i] == '7' || str[i] == '8' || str[i] == '9' || str[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_price.setText("");
                txt_price.requestFocus();
                break;
            }
        }
        char strqty[] = txt_qty.getText().toCharArray();
        for (int i = 0; i < strqty.length; i++) {
            if (!(strqty[i] == '.' || strqty[i] == '1' || strqty[i] == '2' || strqty[i] == '3' || strqty[i] == '4' || strqty[i] == '5' || strqty[i] == '6' || strqty[i] == '7' || strqty[i] == '8' || strqty[i] == '9' || strqty[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_qty.setText("");
                txt_qty.requestFocus();
                break;
            }
        }
        char strtab[] = txt_tab.getText().toCharArray();
        for (int i = 0; i < strtab.length; i++) {
            if (!(strtab[i] == '1' || strtab[i] == '2' || strtab[i] == '3' || strtab[i] == '4' || strtab[i] == '5' || strtab[i] == '6' || strtab[i] == '7' || strtab[i] == '8' || strtab[i] == '9' || strtab[i] == '0')) {
                Tools.msg("Can't save Alphabetic in this field");
                txt_tab.setText("");
                txt_tab.requestFocus();
                break;
            }
        }
        if ("".equals(txt_price.getText()) || "".equals(txt_qty.getText())) {
        } else {
            set();
            //=======================================================================
            if (!"علبة".equals(cmx_type.getSelectedItem())) {
                String Comp_ID = s.getValueByName(cmx_comp.getSelectedItem().toString());
                String update = "update drug set "
                        + "Name = '" + txt_name.getText() + "' , "
                        + "Barcode = '" + txt_bar.getText() + "' , "
                        + "Price = " + Double.parseDouble(txt_price.getText()) + " , "
                        + "Comp_ID = " + Comp_ID + " , "
                        + "Typee = '" + cmx_type.getSelectedItem().toString() + "' , "
                        + "Qty = " + Double.parseDouble(txt_qty.getText())
                        + " where ID = " + Integer.parseInt(txt_ID.getText());
                db.database.RunNonQuery(update);
            } else if ("علبة".equals(cmx_type.getSelectedItem())) {
                String Comp_ID = s.getValueByName(cmx_comp.getSelectedItem().toString());
                String update = "update drug set "
                        + "Name = '" + txt_name.getText() + "' , "
                        + "Barcode = '" + txt_bar.getText() + "' , "
                        + "Price = " + Double.parseDouble(txt_price.getText()) + " , "
                        + "Comp_ID = " + Comp_ID + " , "
                        + "Typee = '" + cmx_type.getSelectedItem().toString() + "' , "
                        + "Qty = " + Double.parseDouble(txt_qty.getText()) + " , "
                        + "Tab = " + Integer.parseInt(txt_tab.getText())
                        + " where ID = " + Integer.parseInt(txt_ID.getText());
                db.database.RunNonQuery(update);
            }
            //=======================================================================
            //s.update();
            clear();
            s.selectAll(tbl);
            /*txt_name.setEditable(true);
            txt_price.setEditable(true);
            txt_tab.setEditable(true);
            cmx_type.setEnabled(true);
            cmx_comp.setEnabled(true);
            btn_addPhone1.setEnabled(true);
            add_comp.setEnabled(true);*/
        }
    }

    private void delete() {
        if (Tools.ConfirmMsg("Are You Sure You Want To Delete this Product permanently?")) {
            set();
            s.delete();
            clear();
            s.selectAll(tbl);
        }
    }

    private String mylike() {
        return " like '%" + txt_search.getText() + "%'";
    }

    private void search() {
        String txtSer;
        String query = "SELECT * FROM `drug_data` WHERE ";
        if (rad_ID.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "ID like '%" + txtSer + "%'";
        } else if (rad_name.isSelected()) {
            txtSer = txt_search.getText();
            query += "Name like '%" + txtSer + "%'";
        } else if (rad_price.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Price like '%" + txtSer + "%'";
        } else if (rad_qty.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Qty like '%" + txtSer + "%'";
        } else if (rad_type.isSelected()) {
            txtSer = Tools.removenum(txt_search.getText());
            query += "Type like '%" + txtSer + "%'";
        } else if (rad_tab.isSelected()) {
            txtSer = Tools.getnum(txt_search.getText());
            query += "Tab like '%" + txtSer + "%'";
        } else {
            query += "Comp_ID" + mylike() + " or Comp_Name" + mylike();
        }
        s.getCustom(query, tbl);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_user.setText(username);
        btngroup.add(rad_ID);
        btngroup.add(rad_bar);
        btngroup.add(rad_comp);
        btngroup.add(rad_name);
        btngroup.add(rad_price);
        btngroup.add(rad_qty);
        btngroup.add(rad_type);
        btngroup.add(rad_tab);
        clear();
        tbl.getTableHeader().setReorderingAllowed(false);
        db.database.FillCombo("company", "Name", "1", cmx_comp);
        s.selectAll(tbl);
    }//GEN-LAST:event_formWindowOpened

    private void btn_addPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPhone1ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btn_addPhone1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        main m = new main(username);
        m.setTitle("Main Menu");
        this.dispose();
        Tools.open(m);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jMyButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton8ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setTitle("Login");
        this.dispose();
        Tools.open(log);
    }//GEN-LAST:event_jMyButton8ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btn_upActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btn_delActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        clear();
        txt_bar.setEditable(true);
        cmx_type.setSelectedIndex(0);
        cmx_comp.setSelectedIndex(0);
        txt_bar.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int row = tbl.getSelectedRow();
        String type = tbl.getValueAt(row, 5).toString();

        txt_ID.setText(tbl.getValueAt(row, 0).toString());
        txt_bar.setText(tbl.getValueAt(row, 1).toString());
        txt_name.setText(tbl.getValueAt(row, 2).toString());
        cmx_comp.setSelectedItem(tbl.getValueAt(row, 4));
        cmx_type.setSelectedItem(tbl.getValueAt(row, 5));
        txt_price.setText(tbl.getValueAt(row, 6).toString());
        txt_qty.setText(tbl.getValueAt(row, 7).toString());
        if ("علبة".equals(type)) {
            txt_tab.setText(tbl.getValueAt(row, 8).toString());
        } else {
            txt_tab.setText("");
        }
        txt_bar.setEditable(false);
        btn_add.setEnabled(false);
        btn_up.setEnabled(true);
        btn_del.setEnabled(true);
    }//GEN-LAST:event_tblMouseClicked

    company c = new company();
    company_phones cp = new company_phones();

    private void add_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_compActionPerformed
        // TODO add your handling code here:
        int DepNO = Integer.parseInt(c.getAutoNumber());
        String Name = (String) Tools.InputBox("Enter Company Name :");
        String Address = (String) Tools.InputBox("Enter Company Address :");
        String phone = (String) Tools.InputBox("Enter at least one Phone for this Company");
        if ("".equals(Name) || "".equals(Address) || "".equals(phone)) {
            Tools.msg("Can't Save Company as value null");
        } else {
            c.setID(DepNO);
            c.setName(Name);
            c.setAddress(Address);
            cp.setID(DepNO);
            cp.setPhone(phone);
            c.add();
            cp.add();
            db.database.FillCombo("company", "Name", "1", cmx_comp);
        }
    }//GEN-LAST:event_add_compActionPerformed

    private void tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            delete();
        }
    }//GEN-LAST:event_tblKeyPressed

    private void txt_tabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tabKeyPressed
        // TODO add your handling code here:
        if (btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                add();
            }
        } else if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_tabKeyPressed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search();
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        clear();
        txt_bar.setEditable(true);
        cmx_type.setSelectedIndex(0);
        cmx_comp.setSelectedIndex(0);
        txt_bar.requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void btn_del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del1ActionPerformed
        // TODO add your handling code here:
        s.selectAll(tbl);
    }//GEN-LAST:event_btn_del1ActionPerformed

    private void cmx_compKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmx_compKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_cmx_compKeyPressed

    private void txt_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_priceKeyPressed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        } else if (btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                add();
            }
        }
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void cmx_typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmx_typeKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_cmx_typeKeyPressed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
        // TODO add your handling code here:
        if (!btn_add.isEnabled()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                update();
            }
        }
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_barKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean check;
            check = db.database.checkinsertion(txt_bar.getText());
            if (check) {
                String sel_ID = "select (ID) from drug where Barcode = '" + txt_bar.getText() + "'";
                String ID = db.database.getTableData(sel_ID).items[0][0].toString();
                String sel_Name = "select (Name) from drug where Barcode = '" + txt_bar.getText() + "'";
                String Name = db.database.getTableData(sel_Name).items[0][0].toString();
                String sel_pri = "select (Price) from drug where Barcode = '" + txt_bar.getText() + "'";
                String price = db.database.getTableData(sel_pri).items[0][0].toString();
                String sel_com = "select (Comp_ID) from drug where Barcode = '" + txt_bar.getText() + "'";
                String com = db.database.getTableData(sel_com).items[0][0].toString();
                String sel_ty = "select (Typee) from drug where Barcode = '" + txt_bar.getText() + "'";
                String type = db.database.getTableData(sel_ty).items[0][0].toString();
                String tab = "";
                if ("علبة".equals(type)) {
                    String sel_tab = "select (Tab) from drug where Barcode = '" + txt_bar.getText() + "'";
                    tab = db.database.getTableData(sel_tab).items[0][0].toString();
                }
                if (!("".equals(ID) || "".equals(Name) || "".equals(price) || "".equals(com) || "".equals(type))) {
                    String company = s.getNameByValue(com);

                    txt_ID.setText(ID);
                    txt_name.setText(Name);
                    txt_price.setText(price);
                    txt_tab.setText(tab);
                    cmx_type.setSelectedItem(type);
                    cmx_comp.setSelectedItem(company);

                    txt_name.setEditable(false);
                    //txt_price.setEditable(false);
                    txt_tab.setEditable(false);
                    cmx_type.setEnabled(false);
                    cmx_comp.setEnabled(false);
                    btn_addPhone1.setEnabled(false);
                    add_comp.setEnabled(false);

                    txt_qty.requestFocus();
                }
            } else {
                txt_name.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_barKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private control.JMyButton add_comp;
    private control.JMyButton btn_add;
    private control.JMyButton btn_addPhone1;
    private control.JMyButton btn_back;
    private control.JMyButton btn_del;
    private control.JMyButton btn_del1;
    private control.JMyButton btn_up;
    private javax.swing.ButtonGroup btngroup;
    private control.JMyCompo cmx_comp;
    private control.JMyCompo cmx_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private control.JMyButton jMyButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JRadioButton rad_ID;
    private javax.swing.JRadioButton rad_bar;
    private javax.swing.JRadioButton rad_comp;
    private javax.swing.JRadioButton rad_name;
    private javax.swing.JRadioButton rad_price;
    private javax.swing.JRadioButton rad_qty;
    private javax.swing.JRadioButton rad_tab;
    private javax.swing.JRadioButton rad_type;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_bar;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tab;
    // End of variables declaration//GEN-END:variables
}
